# Generated by Django 4.1.5 on 2023-02-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='qunatite',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='stockentrant',
            old_name='qunatite',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='stocksortant',
            old_name='qunatite',
            new_name='quantite',
        ),
        migrations.RemoveField(
            model_name='stockentrant',
            name='date',
        ),
        migrations.AddField(
            model_name='stocksortant',
            name='prix',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
